<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tbl_kk', function (Blueprint $table) {
            $table->integer('rumah_id', true);
            $table->text('kk_a')->nullable();
            $table->text('nik_aa')->nullable();
            $table->text('nama_aa')->nullable();
            $table->text('nik_ab')->nullable();
            $table->text('nama_ab')->nullable();
            $table->text('nik_ac')->nullable();
            $table->text('nama_ac')->nullable();
            $table->text('nik_ad')->nullable();
            $table->text('nama_ad')->nullable();
            $table->text('nik_ae')->nullable();
            $table->text('nama_ae')->nullable();
            $table->text('nik_af')->nullable();
            $table->text('nama_af')->nullable();
            $table->text('nik_ag')->nullable();
            $table->text('nama_ag')->nullable();
            $table->text('nik_ah')->nullable();
            $table->text('nama_ah')->nullable();
            $table->text('nik_ai')->nullable();
            $table->text('nama_ai')->nullable();
            $table->text('nik_aj')->nullable();
            $table->text('nama_aj')->nullable();
            $table->text('kk_b')->nullable();
            $table->text('nik_ba')->nullable();
            $table->text('nama_ba')->nullable();
            $table->text('nik_bb')->nullable();
            $table->text('nama_bb')->nullable();
            $table->text('nik_bc')->nullable();
            $table->text('nama_bc')->nullable();
            $table->text('nik_bd')->nullable();
            $table->text('nama_bd')->nullable();
            $table->text('nik_be')->nullable();
            $table->text('nama_be')->nullable();
            $table->text('nik_bf')->nullable();
            $table->text('nama_bf')->nullable();
            $table->text('nik_bg')->nullable();
            $table->text('nama_bg')->nullable();
            $table->text('nik_bh')->nullable();
            $table->text('nama_bh')->nullable();
            $table->text('nik_bi')->nullable();
            $table->text('nama_bi')->nullable();
            $table->text('nik_bj')->nullable();
            $table->text('nama_bj')->nullable();
            $table->text('kk_c')->nullable();
            $table->text('nik_ca')->nullable();
            $table->text('nama_ca')->nullable();
            $table->text('nik_cb')->nullable();
            $table->text('nama_cb')->nullable();
            $table->text('nik_cc')->nullable();
            $table->text('nama_cc')->nullable();
            $table->text('nik_cd')->nullable();
            $table->text('nama_cd')->nullable();
            $table->text('nik_ce')->nullable();
            $table->text('nama_ce')->nullable();
            $table->text('nik_cf')->nullable();
            $table->text('nama_cf')->nullable();
            $table->text('nik_cg')->nullable();
            $table->text('nama_cg')->nullable();
            $table->text('nik_ch')->nullable();
            $table->text('nama_ch')->nullable();
            $table->text('nik_ci')->nullable();
            $table->text('nama_ci')->nullable();
            $table->text('nik_cj')->nullable();
            $table->text('nama_cj')->nullable();
            $table->text('kk_d')->nullable();
            $table->text('nik_da')->nullable();
            $table->text('nama_da')->nullable();
            $table->text('nik_db')->nullable();
            $table->text('nama_db')->nullable();
            $table->text('nik_dc')->nullable();
            $table->text('nama_dc')->nullable();
            $table->text('nik_dd')->nullable();
            $table->text('nama_dd')->nullable();
            $table->text('nik_de')->nullable();
            $table->text('nama_de')->nullable();
            $table->text('nik_df')->nullable();
            $table->text('nama_df')->nullable();
            $table->text('nik_dg')->nullable();
            $table->text('nama_dg')->nullable();
            $table->text('nik_dh')->nullable();
            $table->text('nama_dh')->nullable();
            $table->text('nik_di')->nullable();
            $table->text('nama_di')->nullable();
            $table->text('nik_dj')->nullable();
            $table->text('nama_dj')->nullable();
            $table->text('kk_e')->nullable();
            $table->text('nik_ea')->nullable();
            $table->text('nama_ea')->nullable();
            $table->text('nik_eb')->nullable();
            $table->text('nama_eb')->nullable();
            $table->text('nik_ec')->nullable();
            $table->text('nama_ec')->nullable();
            $table->text('nik_ed')->nullable();
            $table->text('nama_ed')->nullable();
            $table->text('nik_ee')->nullable();
            $table->text('nama_ee')->nullable();
            $table->text('nik_ef')->nullable();
            $table->text('nama_ef')->nullable();
            $table->text('nik_eg')->nullable();
            $table->text('nama_eg')->nullable();
            $table->text('nik_eh')->nullable();
            $table->text('nama_eh')->nullable();
            $table->text('nik_ei')->nullable();
            $table->text('nama_ei')->nullable();
            $table->text('nik_ej')->nullable();
            $table->text('nama_ej')->nullable();
            $table->text('kk_f')->nullable();
            $table->text('nik_fa')->nullable();
            $table->text('nama_fa')->nullable();
            $table->text('nik_fb')->nullable();
            $table->text('nama_fb')->nullable();
            $table->text('nik_fc')->nullable();
            $table->text('nama_fc')->nullable();
            $table->text('nik_fd')->nullable();
            $table->text('nama_fd')->nullable();
            $table->text('nik_fe')->nullable();
            $table->text('nama_fe')->nullable();
            $table->text('nik_ff')->nullable();
            $table->text('nama_ff')->nullable();
            $table->text('nik_fg')->nullable();
            $table->text('nama_fg')->nullable();
            $table->text('nik_fh')->nullable();
            $table->text('nama_fh')->nullable();
            $table->text('nik_fi')->nullable();
            $table->text('nama_fi')->nullable();
            $table->text('nik_fj')->nullable();
            $table->text('nama_fj')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tbl_kk');
    }
};
